[package]
name = "hello"
version = "0.1.0"
edition = "2024"

[dependencies]
cortex-m-rt = "0.7.5"
cortex-m-semihosting = "0.5.0"
embedded-hal = "1.0.0"
panic-halt = "1.0.0"
stm32f4xx-hal = {version="0.22.1", features=["stm32f407"]}
